sudo: required

services:
  - docker

script:
  - |
    export VERSION=$(basename $TRAVIS_BRANCH) &&
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
    docker build -t borgius/node-alpine:${VERSION} . &&

    docker run -ti --rm borgius/node-alpine:${VERSION} ping &&

    docker build -t borgius/node-alpine:${VERSION}-onbuild -f Dockerfile.onbuild . &&
    docker build -t borgius/node-alpine:${VERSION}-development -f Dockerfile.development . &&

    docker push borgius/node-alpine:${VERSION} &&
    docker push borgius/node-alpine:${VERSION}-onbuild &&
    docker push borgius/node-alpine:${VERSION}-development &&
    exit 0 || exit 1
